version: 0.2

# env:
#   parameter-store:
#     DOCKER_REGISTRY_USERNAME: /project1/docker-credentials/username
#     DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
#     DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      # - cd day-13/simple-python-app/
      - echo "Building Docker image..."
      # - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264531732.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t eks-cicd .
      - docker tag eks-cicd:latest 058264531732.dkr.ecr.us-east-1.amazonaws.com/eks-cicd:latest
      - docker push 058264531732.dkr.ecr.us-east-1.amazonaws.com/eks-cicd:latest
      # - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
      # test trigger
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ./

